<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Nivaes.IoC</RootNamespace>
    
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Nivaes.IoC</PackageId>
    <Title>Nivaes IoC</Title>

    <GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
    <Product>Nivaes IoC</Product>
    <Description>Nivaes IoC.</Description>
    <PackageTags>Nivaes;IoC</PackageTags>

    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Nivaes.IoC.Benchmarks" />
    <InternalsVisibleTo Include="Nivaes.IoC.Tests" />
  </ItemGroup>
  
  <ItemGroup>
    <None Include="Images\icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nivaes.IoC.SourceGenerator\Nivaes.IoC.SourceGenerator.csproj" >
      <PrivateAssets>all</PrivateAssets>
      <OutputItemType>Analyzer</OutputItemType>
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
      <IncludeAssets>analyzers</IncludeAssets>
      <ExcludeAssets>runtime; build; native; contentfiles; buildtransitive</ExcludeAssets>
    </ProjectReference>
  </ItemGroup>

</Project>
